### ISSUE TITLE
BUG | 

### ISSUE THREAD

**Issue by Eddippla** [nishi7409/Auxiliary#10]
**Describe the bug**

**To Reproduce**
Add the desired amount of points to the user.

**Expected behavior**
It doesn't promote.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: windoweronies]
 - Browser [flat earth (chrome)]
 - Version [no]

**Additional context**
wasn't that I didn't give perms lmao it just doesnt

**Comment by Eddippla** [comment]
it isnt what happened bfore
k?

**Comment by Nevermindjkl** [comment]
Are you sure you aren't in a rank above the rankbot?

**Comment by nishi7409** [comment]
Can you please follow the format.  It's not that difficult.  Screenshots would be helpful

**Comment by Eddippla** [comment]
I'm promoting someone else.

**Comment by Eddippla** [comment]
how can i give a screenshot

**Comment by Eddippla** [comment]
of something

**Comment by nishi7409** [comment]
link it

**Comment by Eddippla** [comment]
that just doesnt give anything?

**Comment by Eddippla** [comment]
it just doesnt do it? what you want me to link?

**Comment by nishi7409** [comment]
join the server rather than posting this issue here. if you're not going to use the proper channels of communication, find another project

**Comment by Eddippla** [comment]
:p

**Comment by Eddippla** [comment]
:(

**Comment by Eddippla** [comment]
hi im alive

**Comment by Eddippla** [comment]
Ill try one last time the bug,
as I didn't put It welll
