### ISSUE TITLE
BUG | 

### ISSUE THREAD

**Issue by Eddippla** [nishi7409/Auxiliary#9]
**Describe the bug**
The bot doesn't promote.

**To Reproduce**
1. Get someone to the desired points.
2. They won't be promoted.

**Expected behavior**
It doesn't promote the user.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]
 - Version [N/A]

**Additional context**
No

**Comment by longsawk0102** [comment]
Is the bot in the group? If it does, does it have promote permissions?

**Comment by Eddippla** [comment]
No it does not im stupid and ill go kill myself

**Comment by longsawk0102** [comment]
ok go ahead no balls

**Comment by Eddippla** [comment]
lmao

**Comment by nishi7409** [comment]
Niceeeeeee lmao

**Comment by JonatanMGit** [comment]
lmao
